theme: jekyll-theme-cayman
lang: ja
title: 英傑大戦 総プレイ料金ブックマークレット
page_title: 英傑大戦 総プレイ料金ブックマークレット
description: 英傑大戦.NETのデータリストから、総プレイ料金を算出できるブックマークレットです。
plugins:
  - jekyll-sitemap
url: https://boushi-bird.github.io
google_tag_manager: GTM-WFQ64LJ
